### ISSUE TITLE
Send Location Data to Server Periodically

### ISSUE THREAD

**Issue by toton6868** [vipulasri/LocationUpdates#2]
Great Work!!!! Finally something works fluently with my App. I have few things to know. Please help me as you are the Guru of this kind of stuff. Actually I want to send the Location data to server periodically. By using your code I am enable to get the periodic data (longitude and latitude) but its showing on notification bar. I will stop that by removing the code in LocationUpdates.java. But how can I use these location to send periodically in Background rather than sowing on Notification bar. Is there any chance to kill the app by OS or access removal of Fused Location if I stop notifying the updates on Status Bar? I tried to send data using Volley but the App crashed.

**Comment by vipulasri** [comment]
@toton6868 you can definitely do that use [Firebase Job Dispatcher](https://github.com/firebase/firebase-jobdispatcher-android) this will ease your work by managing all the operations when OS kills the app or service running.
